# Generated by Django 3.2.9 on 2022-02-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='completed_value',
            field=models.BooleanField(default=False),
        ),
    ]
